const words = [
    "aberrant",
    "amateur",
    "animal",
    "anorak",
    "ape",
    "ape covered in human flesh",
    "apefucker",
    "arfarfan'arf",
    "arse",
    "arsebreath",
    "arsecunt",
    "arseface",
    "arsehole",
    "arse-licker",
    "ass",
    "assaholic",
    "assbutt",
    "ass clown",
    "asscunt",
    "assface",
    "assfucker",
    "asshat",
    "asshole",
    "ass-kisser",
    "ass-licker",
    "assmonkey",
    "assmouth",
    "assmunch",
    "ass-nugget",
    "ass sucker",
    "asstard",
    "asswagon",
    "assweed",
    "asswipe",
    "aunt fucker",
    "baby",
    "backwoodsman",
    "badass",
    "badgerfucker",
    "bag of dicks",
    "ballkicker",
    "ballsack",
    "bandit",
    "bangsat",
    "barbarian",
    "Barbie-fucker",
    "bastard",
    "bean head",
    "beast",
    "beetlehead",
    "beginner",
    "beldame",
    "bell-end",
    "berk",
    "bespawler",
    "bimbo",
    "birdbrain",
    "birdfucker",
    "bitch",
    "bitchass",
    "bitch ass motherfucker",
    "bitch boy",
    "bitchcunt",
    "bitchface",
    "bitchfucker",
    "bitchtits",
    "bitchwad",
    "bitchwhore",
    "bitchzilla",
    "biznatch",
    "blackguard",
    "blaggard",
    "blockhead",
    "blubber gut",
    "bluntie",
    "bogeyman",
    "bonehead",
    "boob",
    "booby",
    "boomer",
    "bootlicker",
    "boozer",
    "boyfucker",
    "bozo",
    "brickfucker",
    "brickhead",
    "brotherfucker",
    "buffoon",
    "bugfucker",
    "bugger",
    "bullfuck",
    "bum",
    "bumbo",
    "bum chum",
    "bum-fucker",
    "burden",
    "buttass",
    "buttbreath",
    "buttfucker",
    "butthead",
    "butthole",
    "buttkisser",
    "buttlicker",
    "buttmunch",
    "butt sniffer",
    "camelfucker",
    "catfucker",
    "caveman",
    "chauvinist",
    "chav",
    "cheater",
    "chicken",
    "chickenfucker",
    "childfucker",
    "chode",
    "chump",
    "churl",
    "clitbag",
    "clithead",
    "clown",
    "cock",
    "cockalorum",
    "cockboy",
    "cockburger",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockmaster",
    "cockroach",
    "cocksucker",
    "cockwaddle",
    "cockweasel",
    "cockwomble",
    "coffee slurper",
    "con man",
    "con merchant",
    "coomer",
    "corpsefucker",
    "cougar",
    "country bumpkin",
    "cousinfucker",
    "cow",
    "coward",
    "cowfucker",
    "crackhead",
    "crack whore",
    "craphole",
    "creep",
    "cretin",
    "cro magnon",
    "crook",
    "cuckold",
    "cumbucket",
    "cum dumpster",
    "cum guzzler",
    "cum-licker",
    "cumslut",
    "cumstain",
    "cunt",
    "cuntass",
    "cuntbiscuit",
    "cuntbitch",
    "cuntbreath",
    "cuntface",
    "cunt fart",
    "cuntfucker",
    "cuntlicker",
    "cunt muncher",
    "cunt rag",
    "cuntshit",
    "cuntsucker",
    "cuntzilla",
    "dandiprat",
    "daughterfucker",
    "deadhead",
    "degenerate",
    "der-brain",
    "desperado",
    "devil",
    "dick",
    "dickass",
    "dickbag",
    "dickbreath",
    "dickcheese",
    "dickface",
    "dickfucker",
    "dickhead",
    "dickhole",
    "dickless",
    "dicklicker",
    "dick man",
    "dick mouth",
    "dick sniffer",
    "dicksplash",
    "dick-sucker",
    "dicktard",
    "dickwad",
    "dickweasel",
    "dick weed",
    "dildo",
    "dillhole",
    "dimmadumbass",
    "dimwit",
    "ding-head",
    "dingleberry",
    "dinosaur",
    "dipfuck",
    "dirtbag",
    "dirthead",
    "dirtwad",
    "dodo",
    "dog",
    "dogbolt",
    "dogbreath",
    "dogfucker",
    "dolt",
    "donkey",
    "donkey dick",
    "donkeyfucker",
    "doofus",
    "dope",
    "dotterel",
    "douche",
    "douche bag",
    "doucheburger",
    "douche canoe",
    "douchelord",
    "douche nozzle",
    "douchewad",
    "douchewagon",
    "dracula",
    "dreamer",
    "drunkard",
    "duckfucker",
    "dumbarse",
    "dumbass",
    "dumbbell",
    "dumb fucker",
    "dumbo",
    "dummy",
    "dunce",
    "duncebucket",
    "dweebling",
    "earthworm",
    "edgelord",
    "egghead",
    "egotist",
    "envirotard",
    "eunuch",
    "farmer",
    "fart",
    "fartface",
    "fatass",
    "fatfuck",
    "fat geezer",
    "fatherfucker",
    "fatso",
    "fat-tard",
    "fatty",
    "fellow",
    "fetus",
    "fibber",
    "fink",
    "fish",
    "fishwife",
    "fixer",
    "flake",
    "fool",
    "freak",
    "fuck",
    "fuckass",
    "fuckbait",
    "fuckbucket",
    "fucker",
    "fuckface",
    "fuckhead",
    "fucking bitch",
    "fucklord",
    "fuck noggin",
    "fucknose",
    "fuck nugget",
    "fuckrod",
    "fuckskull",
    "fuckstain",
    "fuckster",
    "fucktard",
    "fucktoy",
    "fuckweasel",
    "fuckwhistle",
    "fuckwit",
    "fugly",
    "gawk",
    "geebag",
    "gimp",
    "git",
    "gobshite",
    "gold digger",
    "goof",
    "goon",
    "goose",
    "gorilla",
    "grandmotherfucker",
    "greeniac",
    "grouch",
    "grumpy",
    "handfucker",
    "headass",
    "helldog",
    "hikikomori",
    "hilding",
    "hillbilly",
    "hippie",
    "ho",
    "hobbledehoy",
    "hoe",
    "hog",
    "hooligan",
    "hooplehead",
    "horsefucker",
    "horse's ass",
    "horse's necktie",
    "hosebag",
    "hussy",
    "hypocrite",
    "idiot",
    "idiotist",
    "idiot sandwich",
    "ignoramus",
    "imbecile",
    "inbred",
    "incel",
    "intercourser",
    "jabroni",
    "jackass",
    "jackhole",
    "jackwagon",
    "jagweed",
    "jamoke",
    "jelly",
    "jerk",
    "jerkoff",
    "jerkwad",
    "jit stain",
    "jizz guzzler",
    "joker",
    "junkie",
    "karen",
    "kevun",
    "keyboard warrior",
    "kidfucker",
    "klutz",
    "lady of the evening",
    "lamebrain",
    "landwhale",
    "langer",
    "lard face",
    "liar",
    "libtard",
    "lickspittle",
    "lobotomite",
    "loser",
    "louse",
    "low-life",
    "lunatic",
    "lunkhead",
    "lurdane",
    "lush",
    "mackerel",
    "madman",
    "maggot",
    "mamzer",
    "meanie",
    "megabitch",
    "megadouche",
    "milksop",
    "minx",
    "missing link",
    "mongoose",
    "monkey",
    "monkeyface",
    "monster",
    "mooncalf",
    "moron",
    "motherfucker",
    "mousefucker",
    "mouth breather",
    "Mr. Anger",
    "Mr. Obsessed",
    "Mr. Struggle",
    "Mr. Talk",
    "mucky pup",
    "mumpsimus",
    "muppet",
    "mutant",
    "mutt",
    "neanderthal",
    "neckbeard",
    "necrophiliac",
    "ne'er-do-well",
    "nephew fucker",
    "nerd",
    "nerf herder",
    "niece fucker",
    "nimrod",
    "nincompoop",
    "ninny",
    "ninnyhammer",
    "nitwit",
    "nobody",
    "non",
    "nonce",
    "noob",
    "noodle",
    "numbnuts",
    "numbskull",
    "numpty",
    "numskull",
    "oaf",
    "oddball",
    "ogre",
    "oompa loompa",
    "orphan",
    "outlaw",
    "oxygen thief",
    "pack",
    "pain in the ass",
    "pariah",
    "peasant",
    "pedo",
    "pedophile",
    "penchod",
    "pencil dick",
    "penis face",
    "penis sucker",
    "pervert",
    "pig",
    "pigfucker",
    "piggy-wiggy",
    "pikspiller",
    "pillock",
    "pinhead",
    "pirate",
    "pissbrain",
    "pissbreath",
    "pissface",
    "pleb",
    "plonker",
    "pooface",
    "poohead",
    "poop hole",
    "porno freak",
    "potato",
    "prick",
    "prickface",
    "pseudo-intellectual",
    "pube flosser",
    "pudwhacker",
    "puke bag",
    "pukeball",
    "puppet",
    "pussyboy",
    "pussyfucker",
    "pussy pisser",
    "quack",
    "quat",
    "queer",
    "queer bait",
    "querulant",
    "raasclaat",
    "rabbitfucker",
    "rat",
    "ratcatcher",
    "ratfink",
    "ratfucker",
    "redneck",
    "reject",
    "riff-raff",
    "roaster",
    "robot",
    "rowdy",
    "rudesby",
    "ruffian",
    "runt",
    "sadist",
    "Sam Rea",
    "saprophyte",
    "sausage-masseuse",
    "scobberlotcher",
    "scoundrel",
    "scumbag",
    "scumbreath",
    "scumbutt",
    "scumface",
    "scumfuck",
    "scumhead",
    "scumlord",
    "scumwad",
    "scuzzbag",
    "serf",
    "sewer rat",
    "shark",
    "sheepfucker",
    "sheepshagger",
    "shill",
    "shitass",
    "shitbag",
    "shitball",
    "shitbird",
    "shitbrain",
    "shitbreath",
    "shitbucket",
    "shitbum",
    "shitcunt",
    "shitdick",
    "shit-eater",
    "shitehawk",
    "shitface",
    "shit-for-brains",
    "shitfuck",
    "shitfucker",
    "shitgoblin",
    "shithead",
    "shitizen",
    "shitlord",
    "shitneck",
    "shitnugget",
    "shitpicker",
    "shitpiss",
    "shitpot",
    "shitpuddle",
    "shitsack",
    "shit stain",
    "shitter",
    "shitweasel",
    "shmekl",
    "shrew",
    "shyster",
    "sibling fucker",
    "simp",
    "simpleton",
    "sisterfucker",
    "sister humper",
    "skank",
    "sket",
    "skite",
    "skullfucker",
    "skunk",
    "skunkfucker",
    "slag",
    "slave",
    "sleazewad",
    "sleeze",
    "sleeze bag",
    "slimeface",
    "slob",
    "slut",
    "slutfucker",
    "sluthead",
    "smell-feast",
    "smellfungus",
    "snail",
    "snake",
    "snob",
    "snollygoster",
    "snot",
    "snotball",
    "snotface",
    "snothead",
    "snotwad",
    "snowflake",
    "son of a bitch",
    "son of a motherless goat",
    "son of a whore",
    "sow",
    "spack",
    "sped",
    "sphincter",
    "splenetic",
    "square",
    "stink cunt",
    "stinker",
    "stinkhole",
    "straggot",
    "stupid",
    "swindler",
    "swine",
    "sycophant",
    "thief",
    "thotpocket",
    "thundercunt",
    "titbag",
    "toad",
    "tomato",
    "tool",
    "tree hugger",
    "troglodyte",
    "troll",
    "trollface",
    "turd",
    "turdball",
    "turdbucket",
    "turdpile",
    "twat",
    "twattock",
    "twatwaffle",
    "twerp",
    "twit",
    "twunt",
    "unclefucker",
    "vampire",
    "vandal",
    "vantz",
    "varmint",
    "vermin",
    "vonce",
    "wacko",
    "wallflower",
    "wanker",
    "wank stain",
    "weeze bag",
    "weirdo",
    "whore",
    "whorefucker",
    "whore's-bird",
    "whoreson",
    "windfucker",
    "windsucker",
    "wino",
    "witch",
    "womanizer",
    "wommy",
    "worm",
    "wretch",
    "xenophobe",
    "yahoo",
    "yes-man",
    "yiffer",
    "yonker",
    "yutz",
    "zebrafucker",
    "zitface",
    "zoophile",
    "zounderkite",
]

const phrases = [
    "You're as useless as the 'ueue' in 'queue'.",
    "Mirrors can't talk. Lucky for you, they can't laugh either.",
    "Hey, you have something on your chin... no, the 3rd one down.",
    "You're the reason the gene pool needs a lifeguard.",
    "If I had a face like yours, I'd sue my parents.",
    "Your only chance of getting laid is to crawl up a chicken's butt and wait.",
    "Some day you'll go far... and I hope you stay there.",
    "Aha! I see the fuck-up fairy has visited us again!",
    "You must have been born on a highway cos that's where most accidents happen.",
    "If laughter is the best medicine, your fast must be curing the world.",
    "I'm glad to see you're not letting your education get in the way of your ignorance.",
    "Is your ass jealous of the amount of shit that just came out of your mouth?",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "When I see your face there's not a thing I would change... except the direction I was walking in.",
    "If I had a dollar for every time you said something smart, I'd be broke.",
    "When you were born the doctor threw you out the window and the window threw you back.",
    "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
]

exports.words = words;
exports.phrases = phrases;